apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.bucketName }}
spec:
  forProvider:
    region: {{ .Values.region }}
  providerConfigRef:
    name: {{ .Values.providerConfigRef }}

